server:
  port: 8080
  servlet:
    context-path: /
    session:      timeout: 86400s
    encoding:
      charset: UTF-8
      enabled: true
#      force: true
#      force-request: true
#      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: nanee0706@gmail.com
    password: ubfrhntboefqwijf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  
  security:    user:      name: test
      password: 1234
      
    oauth2:      client:        registration:          naver:
            client-id: NztRq_1Khv7Nf9LoQoyZ
            client-secret: ApJGpd26sT
            scope:            - email
            - name
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider: 
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri:  https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 전달할 때 response라는 KEY값으로 데이터를 전달.
       
  datasource:    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/cgv?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  servlet:    multipart:      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations:
  - /mappers/*xml
  
file:
  path: D:/myProject_CGV/image/